name: Publish to VS Code Marketplace through VSCE
on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - id: nvm
              name: read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              
            - uses: actions/setup-node@v2
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@nuggxyz'
            - run: yarn config set enableImmutableInstalls false
            - run: yarn --immutable
            - run: yarn package
            - run: yarn vsce publish --yarn
              env:
                  VSCE_PAT: ${{ secrets.VSCE_DEPLOY_KEY }}

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: true
